### ISSUE TITLE
Discussion: Add the 'char' primitive type

### ISSUE THREAD

**Issue by bsaleil** [maximecb/zetavm#11]
Because there is no ```char``` primitive type, it is not possible to efficiently implement characters (without wrapping them into objects) for a language targeting ZetaVM.
This is suitable for languages like JavaScript, but not for languages using two different types for strings and chars (e.g. Scheme).

If a ```char``` primitive type is added:

* The ```get_char``` instruction should return a char instead of a string.
To keep the IR concise, the implementation can convert it to a string.
Another option is to keep two instructions (e.g. ```get_char``` and ```get_char_str```) to simplify language implementations.

* Char comparison need to be added.
A single instruction to convert from a ```char``` to an ```int64``` allow the implementation to do chars comparison.
Another option is to add explicit IR instructions to do char comparison (e.g. ```lt_char```, ```le_char```, ...)

**Comment by maximecb** [comment]
It's possible to make one-character strings fairly efficient by using a number of implementation tricks. For instance, JavaScript VMs will represent very short strings by storing them as tagged words... That is, you can represent a few 8-bit unicode chars in an 8-byte word. Another thing that is often done is to have preallocated, interned strings for the first 256 chars, so if you ask me for any one-character string, I can give you a pointer back by indexing into an array.

What I would prefer is to have a scheme/LISP variant that uses the same string model as what ZetaVM supports. This would make for better interoperability with other languages living on the VM IMO. Possibly, the char? operator could simply check if the input is a string of length one, and ZetaVM will try to make strings of length one as efficient as possible (given time, at the moment it's fairly slow overall). What do you think? 

If you really want a char primitive that is distinct from string, another possibility is for you to preallocate objects representing chars into an array (eg: of length 256) in your runtime. This makes it possible to compare these one-char objects reasonably efficiently. There is one level of indirection, but given some BBV magic, this could end up being fast, in cases where the objects are constant.

**Comment by bsaleil** [comment]
I understand that one-char strings can efficiently be implemented by the VM.
My problem is more with the indirection introduced if two different types are needed by a language implementation.

IMO, this makes Scheme implementation less intuitive, and Scheme always represents a big part of the languages used to experiment on VM frameworks (for personal projects, student projects, etc...)

I have mixed feelings about this question because on one side, a new type would ease the language implementations, but on the other side, the use one-char strings greatly simplifies the IR instruction set and the VM.

So maybe the real question is more about "the simplicity of the VM vs the simplicity of the language implementations" rather than the performance.
The same question applies, for example, to closures and you already decided to choose VM simplicity so maybe using one-char strings makes more sense.

**Comment by maximecb** [comment]
I think I would prefer to not have a char type, because it seems redundant. I think that I would rather have language implementation use the same limited set of core types, because it might make interoperability easier. For instance, JS uses one-character strings to represent chars. If Scheme on Zeta uses a separate char type, then some interoperability is lost.

**Comment by maximecb** [comment]
Closing for now.
