### ISSUE TITLE
Consider changing to zlib license for less problematic inclusion into binaries

### ISSUE THREAD

**Issue by JonasT** [maximecb/zetavm#13]
This project appears to be a bytecode VM aimed at any sort of programming language developer seeking a backend. Now before you shoot me, yes the current license is already very liberal and generous. However, there is one point that is a bit problematic:

From my impression (disclaimer: I have just discovered this project) the regular use case appears to be 1. I write a compiler targeting the VM, 2. I write some sort of tool which combines the VM and the bytecode into a single binary. (since unless ZetaVM and/or my own language as a language developer becomes widely popular, this is the only way to make a self-contained binary that is likely to run easily on a wide choice of target systems)

Now given this is the default deployment, this means for compiling a single binary of a hello world, the end user (the programmer using the language to make that hello world program) would already need to include an attribution line into the hello world program for the ZetaVM compiled into it. **The reality is that most people wouldn't expect such a requirement purely from using the standard library & standard compiler, and most likely also won't do it in practice and hence violate the terms without being aware of it.**

Now of course you could ignore that and most likely nobody is going to get sued over it anyway, but for a component that is likely to be included into the final binary even for the most basic programs, a license like the [zlib license](https://en.wikipedia.org/wiki/Zlib_License) (which requires attribution in source code and to not lie about who created the software, but drops the attribution requirement in any sort of binary) might be more suitable.

Feel free to disagree and/or ignore this since attribution is obviously your good right as a creator, I just wanted to bring attention to this potential issue with how it might up being used in practice.

**Comment by maximecb** [comment]
AFAIK, the BSD license is liberal enough for commercial use. I don't think the attribution line is a big issue. Certainly it isn't a difficult problem to correct when spotted?

**Comment by JonasT** [comment]
Sure, but be honest:

After compiling a simple hello world C program, has it ever come up to you that you might need to attribute components the compiler has put in? Unless you explicitly statically linked the C library (which you usually wouldn't) probably not - because nobody thinks of that.

Iin reality most people will miss on this and this will create a bit of a legal grey area. Also, for some minimal tools it might not be that practical to show credits (e.g. if it's not an interactive tool), but the license would still require it.

It's not a big problem, I just wanted to point it might be something worth considering. If you want to stick to the BSD license anyway, feel free to close the ticket. I just thought it was worth pointing out.

**Comment by maximecb** [comment]
Not fundamentally opposed, but I'll wait for now. Would like to hear more opinions on this.
