### ISSUE TITLE
What about debugging?

### ISSUE THREAD

**Issue by Meai1** [maximecb/zetavm#15]
Kinda really important to be able to debug a language once it's done, isn't that a feature of the VM that needs to exist? 
Would be cool if you could just use the same remote debugging protocol that v8 has, i think it's called webkit remote debugging protocol

also what's the status right now, can I make a language on top of zetavm right now, and how?

**Comment by maximecb** [comment]
Right now I added the capability to track source code location on function call sites and asserts. I'm in the process of implementing support for exceptions. Fairly basic but helpful debug features. I may add other things to the IR to enable the implementation of debuggers. To be determined.

How does the V8 debug protocol work?

**Comment by Meai1** [comment]
Ok I just realized that I know a lot less about debuggers that I thought I did, I think any debugging support you decide on is fine.. I was really just anxious about whether you had any plans at all because it is important in my opinion. (My idea was that maybe if you could use the same protocol as GDB/MI or v8, then you could reuse the IDEs that already support those but I think it's not quite that easy and v8 is very javascript specific)

**Comment by maximecb** [comment]
Closing for now.
