### ISSUE TITLE
Compilation errors on Cygwin GCC 5.4.0

### ISSUE THREAD

**Issue by fmonett** [maximecb/zetavm#21]
The following code in runtime.cpp:
/// Undefined value constant
const Value Value::UNDEF(Word)0LL), TAG_UNDEF);

/// Boolean constants
const Value Value::FALSE(Word(0LL), TAG_BOOL);
const Value Value::TRUE(Word(1LL), TAG_BOOL);

/// Numerical constants
const Value Value::ZERO(Word(0LL), TAG_INT32);
const Value Value::ONE(Word(1LL), TAG_INT32);
const Value Value::TWO(Word(2LL), TAG_INT32);

Fails compilation with error:
call of overloaded ‘Word(long long int)’ is ambiguous

Seems the compiler can't make the link between int64_t and long long.
When I add casts to int64_t it works. Perhaps adding ULL instead of LL works too.

**Comment by fmonett** [comment]
ULL does not work. My bad. int64_t is signed after all

**Comment by maximecb** [comment]
Man, I hate this C++ type-ambiguity crap. I really wish there was a way to explicitly name which constructor you want. I will add the casts as you suggest.

**Comment by fmonett** [comment]
This may be compiler-specific though.

**Comment by maximecb** [comment]
It is compiler-specific. I'm using clang on Mac and it doesn't give these errors, but it has given me type ambiguity errors in other areas before.

When we set up automated testing (CI) for this project, it might be wise to compile on both clang and G++.

**Comment by maximecb** [comment]
Fixed :)
