### ISSUE TITLE
Float Constant PI

### ISSUE THREAD

**Issue by Maaarcocr** [maximecb/zetavm#23]
I was thinking that maybe having pi as a float constant could simplify the creation of languages on top on zeta. Am I wrong?

**Comment by werediver** [comment]
Why doesn't `M_PI` from `#include <math.h>` or `#include <cmath>` (optionally prepended with `#define _USE_MATH_DEFINES`) work for this purpose?

**Comment by Maaarcocr** [comment]
Is the M_PI exposed to languages implemented with zetavm?

**Comment by werediver** [comment]
Of course, not. So, you are proposing to introduce an op-code like `PUSH_PI_F32` into the virtual machine?

**Comment by Maaarcocr** [comment]
Yes, exactly.

**Comment by werediver** [comment]
Personally, I don't think it's a good idea. Now you're talking about π as f32. Eventually you'll need π as f64, as well a bunch of others from (Mathematical constant)[https://en.wikipedia.org/wiki/Mathematical_constant] Wikipedia page. People will ask questions like "So, we have π, but not √2? How come?? And what about √3?", and I don't see a good answer for them.

I don't see a problem in defining a number of constants in the target language (like it's done in C, C++, Java and so on — their compilers doesn't provide something built-in).

Maybe @maximecb has something to say, though?

**Comment by Maaarcocr** [comment]
Fair enough. It was just an idea, it's not backed up by any real world example.

**Comment by maximecb** [comment]
I think it's very easy to define your own pi constant, and I want to keep the VM as minimal as possible. The way to go about this would be to define a math package/library people can import and include the pi constant in the exported values.
