### ISSUE TITLE
Floating-point support in the self-hosted Plush parser

### ISSUE THREAD

**Issue by maximecb** [maximecb/zetavm#32]
We now have floating-point support in the VM, and in the C++ Plush compiler (cplush). However, we're still missing support for parsing floats in the self-hosted Plush parser (plush/parser.pls). This is a big missing piece, because the self-hosted parser is the preferred way to write Plush code. It's likely that eventually, the cplush compiler will be deprecated. At the very least, this parser won't be as updated and tested as the self-hosted one.

Adding support for floats is mostly a matter of implementing parsing for float literals in parser.pls. The str_to_float instruction can be used to produce floating-point values from strings. There also needs to be a FloatExpr node type added, with accompanying codegen.

**Comment by maximecb** [comment]
@Maaarcocr I noticed this was missing while testing out the audio API. I'd like this if you completed this last missing piece of floating-point support.

**Comment by Maaarcocr** [comment]
Sure, I'll give it a go! :)

**Comment by Maaarcocr** [comment]
Should we close this?

**Comment by maximecb** [comment]
Yes :)
