### ISSUE TITLE
Audio output API (SDL2)

### ISSUE THREAD

**Issue by maximecb** [maximecb/zetavm#5]
I would like to add SDL2 audio support to Zeta. This would be exposed through a core API that does not expose any of the details of SDL. A new "core/audio" package would be created. See the vm/core.cpp source file.

I would prefer that the API be polling-based rather than callback based (SDL2 does provide an API for this). You would simply pass an array of samples to be written, and you could call a function to know the current buffer state (how many samples haven't been played back yet).

Code sample for SDL2 audio playback with polling/queueing:
https://skia.googlesource.com/third_party/sdl/+/refs/heads/master/test/loopwavequeue.c

SDL wiki reference:
https://wiki.libsdl.org/SDL_QueueAudio

What I have in mind is an API that allows you to output either mono or stereo at a fixed 44100Hz sample rate. The goal is really to make audio playback as simple and newbie-proof as possible. The samples would be provided as an array of float32 samples that would be interleaved, ie:

```
var audioData = [chan 0 sample 0, chan 1 sample 0, chan 0 sample 1, chan 2 sample 1, ...]

var audio = import "core/audio"
var dev = audio.open_output_device(num_channels);
audio.queue_samples(dev, audioData);

// Returns the number of queued samples not yet sent to the hardware
var numSaples = audio.get_queue_size(dev);
```

**Comment by maximecb** [comment]
@maaarcocr Maybe this could interest you, once floating-point support is ready :)

**Comment by Maaarcocr** [comment]
So here I am describing my main doubt about the audio API. 

```
var audioData = [chan 0 sample 0, chan 1 sample 0, chan 0 sample 1, chan 2 sample 1, ...]
```

is ```chan 0 sample 0``` a syntactical addition that we are doing in the parser? Is it like a tuple of floats? I'm not really sure that I understand this notation.

**Comment by maximecb** [comment]
> is chan 0 sample 0 a syntactical addition that we are doing in the parser?

No, I just meant to say that the value for sample 0 of channel 0 goes there.

Maybe we should do the channels non-interleaved instead, with an array of arrays of samples:

var audioData = [ [ /* channel 0 samples */ ], [ /* channel 1 samples */ ] ];

> Does audio.open_output_device(num_channels) return the deviceID of the device that has been opened?

I was thinking we'd support just one output device, but maybe we should use a device ID as you suggest, as that would be more future-proof.

> Does audio.open_output_device(num_channels) return the deviceID of the device that has been opened?

I'd like to make the API simple to use, and part of that would be to avoid having to deal with those details. I suggest we fix the sample rate to 44100 and the buffer size to 4096. We can remove those restrictions later if needed.

> I'm happy to say that I have a first version of the API working and I can make my laptop produce some horrible noise! :D

Sweet! :)
